### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by mekken2** [priyanshu-kumar-IN/Twitter_Bot#1]
Line 19: The value should be changed into int

**Comment by Pranshu-Ranjan** [comment]
Hey bro! Priyanshu I see at line 19 you have declared a function store_last_seen_id(last_seen_id, FILE_NAME):
Which isn't returning anything and you have left the return with no value .
And this might be leading problem ahead in the program causing incompiatble datatypes.
It means instead of integer ,string is there .

Look there and fix it by giving a return value to the function store_last_seen_id(last_seen_id, FILE_NAME):

**Comment by Pranshu-Ranjan** [comment]
You know there are several reasons for occurence of value error and one of this is that your fucntion is not returning anything.

ValueError in Python occurs when you try to perform an operation on a value that doesn’t exist.

**Comment by mekken2** [comment]
I checked that by returning last_seen_id in my code editor but unfortunately it didn't resolved the problem and I am still getting the same error

**Comment by mekken2** [comment]
So, I resolved the problem...It was only because my last_seen_id.txt file was empty and I was trying to extract something from it and converting it to Integer.
Just a little thing not even a bug ate up that much of my time!
